[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio
board_build.sdkconfig_options =
    CONFIG_ESP_TASK_WDT_ENABLED=n
    CONFIG_ESP_INT_WDT=n
    CONFIG_ESP_TASK_WDT_TIMEOUT_S=60
